"""Rabit on-chain contract artifacts and backend SDK helpers."""
from .models import (
    AiUsageRecordAccount,
    ContractDeployment,
    ContractDeploymentStatus,
    DelegatedSignerAccount,
    InstructionAccountMetaDef,
    ModelRegistryAccount,
    PlatformConfigAccount,
    ProgramAccountSnapshot,
    SpendingProfileAccount,
)
from .registry import get_contract_root, get_program_id, load_deployment, load_idl
from .sdk import RabitContractSDK, get_rabit_contract_sdk
from .seeds import (
    AI_USAGE_SEED,
    ASSOCIATED_TOKEN_PROGRAM_ID,
    CONFIG_SEED,
    DELEGATED_SIGNER_SEED,
    FEE_RECIPIENT_SEED,
    MODEL_REGISTRY_SEED,
    SPENDING_PROFILE_SEED,
    derive_ai_usage_pda,
    derive_associated_token_account,
    derive_config_pda,
    derive_delegated_signer_pda,
    derive_fee_recipient_pda,
    derive_model_registry_pda,
    derive_spending_profile_pda,
    to_on_chain_model_id,
)

__all__ = [
    "AI_USAGE_SEED",
    "ASSOCIATED_TOKEN_PROGRAM_ID",
    "AiUsageRecordAccount",
    "CONFIG_SEED",
    "ContractDeployment",
    "ContractDeploymentStatus",
    "DELEGATED_SIGNER_SEED",
    "DelegatedSignerAccount",
    "FEE_RECIPIENT_SEED",
    "InstructionAccountMetaDef",
    "MODEL_REGISTRY_SEED",
    "ModelRegistryAccount",
    "PlatformConfigAccount",
    "ProgramAccountSnapshot",
    "RabitContractSDK",
    "SPENDING_PROFILE_SEED",
    "SpendingProfileAccount",
    "derive_ai_usage_pda",
    "derive_associated_token_account",
    "derive_config_pda",
    "derive_delegated_signer_pda",
    "derive_fee_recipient_pda",
    "derive_model_registry_pda",
    "derive_spending_profile_pda",
    "get_contract_root",
    "get_program_id",
    "get_rabit_contract_sdk",
    "load_deployment",
    "load_idl",
    "to_on_chain_model_id",
]
